spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables
    show-sql: true
  kafka:
     bootstrap-servers: localhost:9092
     producer:
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}