spring:
  Kafka:
    # Routes traffic inside the container network to the KRaft internal port
    bootstrap-servers: Kafka:29094

  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification_db